apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APP_NAME}-template
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    generation: 1
    name: ${IMAGE_STREAM_NAME}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
parameters:
  - name: IMAGE_STREAM_NAME 
    required: true 